spring:
  datasource:
    url: jdbc:postgresql://maglev.proxy.rlwy.net:30637/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate